name: example

on: push

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my first job.
  job_02:
    runs-on: windows-latest
    steps:
      - name: job2
        run: echo Hi my helloworld
